name: Flask CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Create and activate virtual environment
      run: |
        python3.12 -m venv venv
        source venv/bin/activate
        pip install flask gunicorn

    - name: Restart Flask App
      run: sudo systemctl restart flask-app
